### ISSUE TITLE
Cant change default object value after first init

### ISSUE THREAD

**Issue by igolka97** [HAlex/vue-reactive-storage#2]
<img width="1287" alt="Снимок экрана 2023-05-09 в 17 22 15" src="https://github.com/AlexDicy/vue-reactive-localstorage/assets/3520658/1f59b9af-9d1f-4580-aef1-e67c84f0f89f">

Having this error. I will look forward to fix it.

**Comment by AlexDicy** [comment]
Can you share the code you're using to enable the plugin? (`Vue.use(...) [...]` etc.)?

**Comment by igolka97** [comment]
Sure. Here it is:

```js
import ReactiveStorage from 'vue-reactive-localstorage'

export default async ({ Vue }) => {
  Vue.use(ReactiveStorage, {
    someEndpoing: 'http://localhost:4400/',
    someObject: {
      someId: false,
      someTime: false
    },
...
```

Note that i'm booting with Quasar boot file.

Hope this part is enough. Another ones looks the same.

**Comment by AlexDicy** [comment]
Yeah, I don't see anything strange with your code.
As long as you're using Vue 2 it should be working fine.
I see that Quasar 2 is based on Vue 3, which might be incompatible with this package

**Comment by igolka97** [comment]
I'm using Quasar v1, that uses Vue 2. Ok, don't worry, i'll debug this issue.

**Comment by igolka97** [comment]
Cant understand why your declarataion of
`_objectDefaults(object, storage)` is default object at first arg, then existing storage at second arg, but in the recursion you use inversed:
`this._objectDefaults(storage[key], value);`

**Comment by AlexDicy** [comment]
Interesting catch, indeed I think it should be inversed as you pointed out

**Comment by igolka97** [comment]
Still let me time, i'm looking around

**Comment by igolka97** [comment]
#3 review my PR please
